# Generated by Django 3.1.7 on 2021-04-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(blank=True, max_length=90)),
                ('LAST_NAME', models.CharField(blank=True, max_length=90)),
                ('Gender', models.CharField(blank=True, max_length=90)),
                ('Hospital_Name', models.CharField(blank=True, max_length=90)),
                ('Phone', models.CharField(max_length=11)),
                ('REVIEW', models.CharField(blank=True, max_length=890)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
